Multiclass classification On Airlines Delay Dataset.

In [2]:
import pandas as pd     # Importing important laibraries for the project
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings("ignore")

from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils #one hot encoding
from sklearn.model_selection import KFold
from sklearn.model_selection import train_test_split,cross_val_score
from sklearn.preprocessing import LabelEncoder

In [3]:
df_air=pd.read_csv("/content/airlines_delay.csv")    # reading the csv file using read_csv function

In [4]:
df_air.head()    # printing top records of the file/dataset.

Flight    Time  Length Airline AirportFrom AirportTo  DayOfWeek  Class
0  2313.0  1296.0   141.0      DL         ATL       HOU          1      0
1  6948.0   360.0   146.0      OO         COS       ORD          4      0
2  1247.0  1170.0   143.0      B6         BOS       CLT          3      0
3    31.0  1410.0   344.0      US         OGG       PHX          6      0
4   563.0   692.0    98.0      FL         BMI       ATL          4      0

In [5]:
df_air.info()   #getting information about the columns and attributes

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 539382 entries, 0 to 539381
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype  
---  ------       --------------   -----  
 0   Flight       539382 non-null  float64
 1   Time         539382 non-null  float64
 2   Length       539382 non-null  float64
 3   Airline      539382 non-null  object 
 4   AirportFrom  539382 non-null  object 
 5   AirportTo    539382 non-null  object 
 6   DayOfWeek    539382 non-null  int64  
 7   Class        539382 non-null  int64  
dtypes: float64(3), int64(2), object(3)
memory usage: 32.9+ MB


In [6]:
df_air.describe()  # getting statistical information of the dataset.

Flight           Time         Length      DayOfWeek  \
count  539382.000000  539382.000000  539382.000000  539382.000000   
mean     2427.927988     802.728161     132.202104       3.929666   
std      2067.431700     278.045546      70.117045       1.914666   
min         1.000000      10.000000       0.000000       1.000000   
25%       712.000000     565.000000      81.000000       2.000000   
50%      1809.000000     795.000000     115.000000       4.000000   
75%      3745.000000    1035.000000     162.000000       5.000000   
max      7814.000000    1439.000000     655.000000       7.000000   

               Class  
count  539382.000000  
mean        0.445443  
std         0.497015  
min         0.000000  
25%         0.000000  
50%         0.000000  
75%         1.000000  
max         1.000000

In [7]:
df_air.isna().sum() #checking any NAN values is present

Flight         0
Time           0
Length         0
Airline        0
AirportFrom    0
AirportTo      0
DayOfWeek      0
Class          0
dtype: int64

In [8]:
df=df_air.dropna(axis=0)  # removing NAN rows using dropna function. 

In [9]:
df.isna().sum()   # NAN are removed.

Flight         0
Time           0
Length         0
Airline        0
AirportFrom    0
AirportTo      0
DayOfWeek      0
Class          0
dtype: int64

In [10]:
x=df.iloc[:,:-1].values  # converting dataframe into numpy array
y=df.iloc[:,-1].values

In [11]:
x

array([[2313.0, 1296.0, 141.0, ..., 'ATL', 'HOU', 1],
       [6948.0, 360.0, 146.0, ..., 'COS', 'ORD', 4],
       [1247.0, 1170.0, 143.0, ..., 'BOS', 'CLT', 3],
       ...,
       [5209.0, 827.0, 74.0, ..., 'CAE', 'ATL', 2],
       [607.0, 715.0, 65.0, ..., 'BWI', 'BUF', 4],
       [6377.0, 770.0, 55.0, ..., 'CPR', 'DEN', 2]], dtype=object)

In [12]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [13]:
le=LabelEncoder() #  converting categorical data into continuous data using Labelencoder for column Airline.
x[:,3]=le.fit_transform(x[:,3])

In [14]:
le=LabelEncoder() # converting categorical data into continuous data using Labelencoder for column AirportFrom.
x[:,4]=le.fit_transform(x[:,4])

In [15]:
le=LabelEncoder() # converting categorical data into continuous data using Labelencoder for column  AirportTo.
x[:,5]=le.fit_transform(x[:,5])

In [16]:
x  # after encoding values of X

array([[2313.0, 1296.0, 141.0, ..., 16, 129, 1],
       [6948.0, 360.0, 146.0, ..., 65, 208, 4],
       [1247.0, 1170.0, 143.0, ..., 35, 60, 3],
       ...,
       [5209.0, 827.0, 74.0, ..., 47, 16, 2],
       [607.0, 715.0, 65.0, ..., 45, 43, 4],
       [6377.0, 770.0, 55.0, ..., 67, 79, 2]], dtype=object)

In [17]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.2, random_state=1) # Splitting the data using train_test_split.

In [18]:
from sklearn.preprocessing import StandardScaler 

In [19]:
sc=StandardScaler() # Scaling the data using StandardScaler.
xtrain=sc.fit_transform(xtrain)
xtest=sc.transform(xtest)

In [20]:
ann=Sequential()   #step 1: Initialize ANN model

In [21]:
# step 2: Adding layers
ann.add(Dense(units=6,activation="relu"))#i/p layer
ann.add(Dense(units=4,activation="relu"))#hidden layer
ann.add(Dense(units=1,activation="softmax"))#output layer


In [22]:
# Step 3: Establish connection
ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

In [23]:
# Step 4: Train model
ann.fit(xtrain,ytrain,epochs=100)

Epoch 1/100
13485/13485 [==============================] - 20s 1ms/step - loss: 0.6659 - accuracy: 0.4451
Epoch 2/100
13485/13485 [==============================] - 18s 1ms/step - loss: 0.6625 - accuracy: 0.4451
Epoch 3/100
13485/13485 [==============================] - 19s 1ms/step - loss: 0.6614 - accuracy: 0.4451
Epoch 4/100
13485/13485 [==============================] - 18s 1ms/step - loss: 0.6602 - accuracy: 0.4451
Epoch 5/100
13485/13485 [==============================] - 19s 1ms/step - loss: 0.6553 - accuracy: 0.4451
Epoch 6/100
13485/13485 [==============================] - 18s 1ms/step - loss: 0.6489 - accuracy: 0.4451
Epoch 7/100
13485/13485 [==============================] - 18s 1ms/step - loss: 0.6412 - accuracy: 0.4451
Epoch 8/100
13485/13485 [==============================] - 18s 1ms/step - loss: 0.6367 - accuracy: 0.4451
Epoch 9/100
13485/13485 [==============================] - 18s 1ms/step - loss: 0.6352 - accuracy: 0.4451
Epoch 10/100
13485/13485 [====================

In [24]:
# Step 5: Predicting actual and predicted values..
pred=ann.predict(xtest)
air_length=len(pred)

3372/3372 [==============================] - 3s 937us/step


In [25]:
ylabel=np.argmax(ytest)#actual
predlabel=np.argmax(pred)#predicted

In [26]:
ylabel

2

In [27]:
predlabel

107872

In [28]:
ac=np.sum(ylabel==predlabel)/air_length*100
print(f"Accuracy:{ac}")

Accuracy:0.0


In [32]:
def airmodel():  # creating function named airmodel for the model.
  ann=Sequential()

  ann.add(Dense(units=6,activation="relu"))#i/p layer
  ann.add(Dense(units=4,activation="relu"))#hidden layer
  ann.add(Dense(units=1,activation="softmax"))#output layer

  ann.compile(optimizer="adam",loss="binary_crossentropy",metrics=["accuracy"])

  ann.fit(xtrain,ytrain,epochs=100)
  return ann

In [ ]:
#  Evaluating the model.
estimator = KerasClassifier(build_fn= airmodel, epochs=200, batch_size=5, verbose=0 )
cvs = cross_val_score(estimator, x,y, cv=10)
print(f"Avg Accuracy -: {cvs.mean()*100}\nSTD : {cvs.std()}")


13485/13485 [==============================] - 21s 2ms/step - loss: 0.6385 - accuracy: 0.4451
Epoch 17/100
13485/13485 [==============================] - 21s 2ms/step - loss: 0.6385 - accuracy: 0.4451
Epoch 18/100
13485/13485 [==============================] - 21s 2ms/step - loss: 0.6381 - accuracy: 0.4451
Epoch 19/100
13485/13485 [==============================] - 21s 2ms/step - loss: 0.6380 - accuracy: 0.4451
Epoch 20/100
13485/13485 [==============================] - 21s 2ms/step - loss: 0.6376 - accuracy: 0.4451
Epoch 21/100
13485/13485 [==============================] - 21s 2ms/step - loss: 0.6374 - accuracy: 0.4451
Epoch 22/100
13485/13485 [==============================] - 21s 2ms/step - loss: 0.6374 - accuracy: 0.4451
Epoch 23/100
 2568/13485 [====>.........................] - ETA: 15s - loss: 0.6377 - accuracy: 0.4460